/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class StartQuiz extends javax.swing.JFrame {

    /**
     * Creates new form EnterQuestions
     */
    Statement stmt;
    ResultSet rs;
    public StartQuiz() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    ResultSet getResult()
    {
        return rs;
    }
    void loadResult()
    {
        String subjCode = cmbSubject.getSelectedItem().toString().substring(0,3); 
        String chaptCode = cmbChapter.getSelectedItem().toString().substring(0,3);
        String subTopicCode = cmbSubTopic.getSelectedItem().toString().substring(0,3);
        String qCode = subjCode+""+chaptCode+""+subTopicCode;
        
        DBConnection ob = new DBConnection();
        try
        {
            String query = "Select * from questionstable where qCode = '"+qCode+"'";            
            stmt = ob.getDBConnection().createStatement();
            rs = stmt.executeQuery(query);
            btnLoad.setText("Loaded");
            btnLoad.setForeground(Color.green);
            txtaQuestion.setText("Ok");
            txtaExplanation.setText("Ok");
            txtChoiceA.setText("Ok");
            txtChoiceB.setText("Ok");
            txtChoiceC.setText("Ok");
            txtChoiceD.setText("Ok");
        }
        catch(SQLException e)
        {
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StartQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblQuestion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaQuestion = new javax.swing.JTextArea();
        lblExplanation = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaExplanation = new javax.swing.JTextArea();
        lblChoiceA = new javax.swing.JLabel();
        txtChoiceA = new javax.swing.JTextField();
        lblChoiceB = new javax.swing.JLabel();
        txtChoiceB = new javax.swing.JTextField();
        lblChoiceC = new javax.swing.JLabel();
        txtChoiceC = new javax.swing.JTextField();
        lblChoiceD = new javax.swing.JLabel();
        txtChoiceD = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmbSubject = new javax.swing.JComboBox<>();
        lblSubject = new javax.swing.JLabel();
        cmbChapter = new javax.swing.JComboBox<>();
        lblChapter = new javax.swing.JLabel();
        lblSubTopic = new javax.swing.JLabel();
        cmbSubTopic = new javax.swing.JComboBox<>();
        btnExplanation = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ALL THE BEST");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Question:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblQuestion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuestion.setText("Question :");

        txtaQuestion.setColumns(20);
        txtaQuestion.setRows(5);
        jScrollPane1.setViewportView(txtaQuestion);

        lblExplanation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExplanation.setText("Explanation:");

        txtaExplanation.setColumns(20);
        txtaExplanation.setRows(5);
        jScrollPane2.setViewportView(txtaExplanation);

        lblChoiceA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChoiceA.setText("Choice A:");

        txtChoiceA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtChoiceA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChoiceAMouseClicked(evt);
            }
        });

        lblChoiceB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChoiceB.setText("Choice B:");

        txtChoiceB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtChoiceB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChoiceBMouseClicked(evt);
            }
        });

        lblChoiceC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChoiceC.setText("Choice c:");

        txtChoiceC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtChoiceC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChoiceCMouseClicked(evt);
            }
        });

        lblChoiceD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChoiceD.setText("Choice D:");

        txtChoiceD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtChoiceD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChoiceDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExplanation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChoiceC)
                        .addGap(220, 220, 220)
                        .addComponent(lblChoiceD)
                        .addGap(18, 18, 18)
                        .addComponent(txtChoiceD, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtChoiceC, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblChoiceA)
                                .addGap(18, 18, 18)
                                .addComponent(txtChoiceA, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(lblChoiceB)
                        .addGap(18, 18, 18)
                        .addComponent(txtChoiceB, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExplanation)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChoiceA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtChoiceA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChoiceB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtChoiceB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChoiceC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtChoiceC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChoiceD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtChoiceD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Questions From:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cmbSubject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSubjectItemStateChanged(evt);
            }
        });
        cmbSubject.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbSubjectFocusGained(evt);
            }
        });

        lblSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSubject.setText("Subject :");

        cmbChapter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbChapterItemStateChanged(evt);
            }
        });

        lblChapter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblChapter.setText("Chapter :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbChapter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbChapter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblChapter))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSubject)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblSubTopic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSubTopic.setText("SubTopic :");

        btnExplanation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExplanation.setText("EXPLANATION");
        btnExplanation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExplanationActionPerformed(evt);
            }
        });

        btnLoad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoad.setText("LOAD");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 311, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSubTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSubTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(317, 317, 317))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnExplanation)
                .addGap(47, 47, 47)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTopic)
                    .addComponent(cmbSubTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExplanation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(410, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HomeWindow ob = new HomeWindow();
        ob.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbSubjectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbSubjectFocusGained
        // TODO add your handling code here:
        try
        {
            DBConnection ob = new DBConnection();
            String query = "SELECT DISTINCT subject FROM datatable";
            Statement stmt = ob.getDBConnection().createStatement();
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next())
            {
                cmbSubject.addItem(rs.getString("subject"));
            }
            ob.getDBConnection().close();
        }
        catch (Exception e)
        {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_cmbSubjectFocusGained

    private void cmbSubjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSubjectItemStateChanged
        // TODO add your handling code here:
        cmbChapter.removeAllItems();
        try
        {
            DBConnection ob = new DBConnection();
            
            String query = "SELECT DISTINCT chapter FROM datatable where subject='"+cmbSubject.getSelectedItem()+"'";
            Statement stmt = ob.getDBConnection().createStatement();
            ResultSet rs = stmt.executeQuery(query);
            //cmbChapter.removeItemAt(0);
            while(rs.next())
            {
                cmbChapter.addItem(rs.getString("chapter"));
            }
            ob.getDBConnection().close();
        }
        catch (Exception e)
        {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_cmbSubjectItemStateChanged

    private void cmbChapterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbChapterItemStateChanged
        // TODO add your handling code here:
        cmbSubTopic.removeAllItems();
        try
        {
            DBConnection ob = new DBConnection();
            String query = "SELECT DISTINCT subtopic FROM datatable where chapter='"+cmbChapter.getSelectedItem()+"'";
            Statement stmt = ob.getDBConnection().createStatement();
            ResultSet rs = stmt.executeQuery(query);
            //cmbChapter.removeItemAt(0);
            while(rs.next())
            {
                cmbSubTopic.addItem(rs.getString("subtopic"));
            }
            ob.getDBConnection().close();
        }
        catch (Exception e)
        {
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_cmbChapterItemStateChanged

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        loadResult();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        txtChoiceA.setBackground(Color.WHITE);
        txtChoiceB.setBackground(Color.WHITE);
        txtChoiceC.setBackground(Color.WHITE);
        txtChoiceD.setBackground(Color.WHITE);
        txtaExplanation.setText("");
        btnLoad.setText("LOAD");
        btnLoad.setForeground(Color.BLACK);
        try {
            if(getResult().next())
            {
                txtaQuestion.setText(getResult().getString("question"));
                txtChoiceA.setText(getResult().getString("choiceA"));
                txtChoiceB.setText(getResult().getString("choiceB"));
                txtChoiceC.setText(getResult().getString("choiceC"));
                txtChoiceD.setText(getResult().getString("choiceD"));
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Questions Over..");
            }
        } catch (SQLException ex) {
            Logger.getLogger(StartQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void txtChoiceAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChoiceAMouseClicked
        try {
            if(getResult().getString("answer").equals("Choice A"))
            {
                txtChoiceA.setBackground(Color.GREEN);
            }
            else
                txtChoiceA.setBackground(Color.RED);
        } catch (SQLException ex) {
            Logger.getLogger(StartQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtChoiceAMouseClicked

    private void btnExplanationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplanationActionPerformed
        try {
            txtaExplanation.setText(getResult().getString("explanation"));
        } catch (SQLException ex) {
            Logger.getLogger(StartQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExplanationActionPerformed

    private void txtChoiceBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChoiceBMouseClicked
        try {
            if(getResult().getString("answer").equals("Choice B"))
            {
                txtChoiceB.setBackground(Color.GREEN);
            }
            else
                txtChoiceB.setBackground(Color.RED);
        } catch (SQLException ex) {
            Logger.getLogger(StartQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtChoiceBMouseClicked

    private void txtChoiceCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChoiceCMouseClicked
        try {
            if(getResult().getString("answer").equals("Choice C"))
            {
                txtChoiceC.setBackground(Color.GREEN);
            }
            else
                txtChoiceC.setBackground(Color.RED);
        } catch (SQLException ex) {
            Logger.getLogger(StartQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtChoiceCMouseClicked

    private void txtChoiceDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChoiceDMouseClicked
        try {
            if(getResult().getString("answer").equals("Choice D"))
            {
                txtChoiceD.setBackground(Color.GREEN);
            }
            else
                txtChoiceD.setBackground(Color.RED);
        } catch (SQLException ex) {
            Logger.getLogger(StartQuiz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtChoiceDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExplanation;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cmbChapter;
    private javax.swing.JComboBox<String> cmbSubTopic;
    private javax.swing.JComboBox<String> cmbSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChapter;
    private javax.swing.JLabel lblChoiceA;
    private javax.swing.JLabel lblChoiceB;
    private javax.swing.JLabel lblChoiceC;
    private javax.swing.JLabel lblChoiceD;
    private javax.swing.JLabel lblExplanation;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblSubTopic;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JTextField txtChoiceA;
    private javax.swing.JTextField txtChoiceB;
    private javax.swing.JTextField txtChoiceC;
    private javax.swing.JTextField txtChoiceD;
    private javax.swing.JTextArea txtaExplanation;
    private javax.swing.JTextArea txtaQuestion;
    // End of variables declaration//GEN-END:variables
}
